language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
jobs:
  include:
    - stage: unit test
      script:
      - cd server
      - gradle build
    - stage: code scan
      script:
      - cd server
      - gradle sonarqube
